type: app
description: Project destined to create a simple yaml file to create the structures ECR, S3 Bucket, Dynamo Table and Lambda Function using the cloudformation tecnology.
template: cloudformation-stack/cloudformation-stack-template